#!/usr/bin/env python3
"""
group_attention.py — the SOLE assembler of prompt Block 2 (circle_objectives):
circle_briefing_build(chosen), constructed fresh at every circle open, live or
sandbox alike. The operator, 2026-09-02: "a group_attention.py ... responsible for
every prompt element written to Block 2 ... none aware of any of the
others, all of the code responsible for those fragment assemblies exists
exclusively in the corresponding single file." docs/CIRCLE_TYPES_DESIGN.md
has the assessment this build follows; docs/BNF.md's circle_briefing_build(chosen)
production (BLOCK 2) is the grammar this implements.

MOVED VERBATIM from prompt_build.py's circle_briefing_build(), 2026-09-02 — same
name, same body, same docstring, so its 50+ existing external callers (grep
confirms callers across coordinator/, memory/, work/ablations/, work/tools/)
keep working unchanged via prompt_build.py's own re-export.

ISSUE_MODEL and read_ro() MOVED HERE, then MOVED AGAIN, same day. Both were
exclusive to this function when this module was built (grep confirmed
ISSUE_MODEL had no other reader) — that stayed true for the length of one
edit. On direct instruction, the same move topics.toml (-> topic_prompt_projection.py)
and parts/<p>/* (-> parts_prompt_projection.py) already made this same day: the
prologue is issue-graph material, issue_prompt_projection.py's to hold, not this
assembler's just because it happens to read the file directly. See
issue_prompt_projection.issue_prologue_read() — this module now calls it rather than reading
the file itself.
"""

from __future__ import annotations


def circle_briefing_build(chosen: list[str]) -> tuple[str, list[str]]:
    """CONSTRUCTED per circle, at its initialisation — the ONLY way
    circle_objectives (BLOCK 2) is built, for every circle, live or sandbox
    alike. Retired 2026-08-11: `self/circle_briefing.md` no longer exists.
    Up to five parts, in order (part 5 added 2026-08-15, R184 — the TOPIC
    register's open topics, coordinator/topic_manager.py, "" while the register is
    empty; everything after part 2 was excluded under --minimal, retired
    R360):

        1  issues/issue_model.md    the prologue. What an issue IS. The one
                                    part present unconditionally.
        2  ## Issues                RICH — see below. Working-set aware: id, name and
                                    detail for each chosen node, and for each
                                    a live edge reaches.
        3  relations, BRIEF         The
                                    five type names glossed, and the live
                                    edges. Generated by issue_prompt_projection, never
                                    transcribed from docs/issue_relationship_types.md (archived)
                                    (which left the tree at 048ccda, 2026-09-07).
        4  issues_narrative.md      RETIRED — B46, 2026-08-17. The
                                    hand-written account that predated the
                                    graph was retired 2026-08-14 once its
                                    remaining entries were migrated in
                                    (commit 16cd565) and never came back;
                                    the read-and-concatenate call site
                                    (issue_prompt_projection.narrative()) had
                                    returned "" on every live circle since
                                    and was dead code. Removed along with
                                    its docs/BNF.md production.

    THE ISSUES ARE RICH, the one shape now (project_working_set): blank
    working set — every live node via block(), label, provenance ("ruled by
    Self in <circle>" or "NOT YET RULED") and its absence clause; chosen
    working set — FOCUS nodes get full detail (description + absence +
    provenance + live edges), PERIPHERY nodes name + description only. A
    FLAT variant (uniform name + description, no provenance, no edges)
    served the --minimal baseline alone — ruled 2026-08-11 that live
    circles keep the richer detail — and retired with that mode (R360).

    `self/circle_briefing.md` is GONE, not merely unread. It was a generated
    intermediate — nightly synthesis wrote it, circle.py read it back — and
    every one of its sections was already sourced from a file that owns its
    own content (issue_model.md, the live issues/*.toml graph, and, at the
    time, issues_narrative.md — itself since retired, B46 2026-08-17). This
    reads what remains directly, the same move R133-137 made for best
    practices and better options: no projection step, no derivation, no
    file in between to go stale.

    THE PROLOGUE HAS A HOME. `## What is here` used to live only inside the
    old generated briefing — 1,838 characters of the issue model with no
    source of truth, which any regeneration would have destroyed. Self
    supplied it verbatim on 2026-08-03 and it is now a file.

    PART 3 IS GENERATED, NOT COPIED, FOR LIVE CIRCLES — new as of 2026-08-11.
    Live circles never carried a relations brief before (self/circle_briefing.md
    had no such section); circle_briefing_build() gives them the one minimal circles
    already had (that mode itself lost it the same session, and retired R360)
    (see above). `docs/issue_relationship_types.md (archived)` was sent whole into
    circle_2026-08-03_2208 — 1,808 tokens, 31% of a part's prompt — and
    across 27 part statements not one edge type was named once. It is an
    engineer's document: file paths, an edge census, a bug history, a section
    called "Where the machinery is". It stays, for me. Live parts get
    `issue_prompt_projection.issue_relationship_brief()`: the five words glossed, and what is live.

    Fails CLOSED on a missing issue_model.md: a briefing assembled without
    the prologue is a different experiment wearing the same name — enforced
    by issue_prompt_projection.issue_prologue_read() itself now, called first, below, so the
    failure still lands before any other part 2-5 work starts. Parts 3 and
    4 are the exception — see above."""
    import issue_prompt_projection as IP
    prologue = IP.issue_prologue_read()   # fails closed on a missing file — see above
    # `chosen is None` IS `none` — finding 2's own answer, 2026-08-20, and
    # a different thing from `[]`. An empty list means "no FOCUS, project
    # the whole live graph"; None means the operator asked for NO ISSUES,
    # and this circle carries the prologue and nothing else. Collapsing
    # them would make `none` a synonym for blank, which is exactly the
    # distinction the ruled grammar draws.
    if chosen is None:
        issues, unknown = ("## Issues\n\n(None this circle. The graph was "
                           "deliberately not brought in.)", [])
    else:
        issues, unknown = IP.project_working_set(chosen)
    parts = [prologue, "", issues.rstrip("\n")]
    # PART 3 — see this function's docstring. Part 4 (the narrative) was
    # retired whole, B46 2026-08-17 — see the docstring's part-4 note.
    # ...and `none` takes the relations brief with it: a brief about edges
    # between issues that are not here would describe nothing this circle
    # can see.
    if chosen is not None:
        parts += ["", "---", "", IP.issue_relationship_brief(chosen).rstrip("\n")]
    # PART 5 — the TOPIC register (R184, 2026-08-15): SYNTHESIS's unvetted
    # BLOCK 2 material, open topics only, newest-first within its window
    # (coordinator/topic_manager.py, projected by topic_prompt_projection.py — split out
    # 2026-09-02, the same move group_context.py/role_context.py already
    # made for their own registers). "" while the register is empty, so
    # this line changes no briefing byte until SYNTHESIS ships a writer.
    import topic_prompt_projection as TP
    top = TP.topic_block_render()
    if top:
        parts += ["", "---", "", top.rstrip("\n")]
    return "\n".join(parts) + "\n", unknown
